# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.manager.seccion:
        class: AppBundle\Manager\SeccionManager
        arguments:
            # dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: AppBundle\Entity\Seccion
    app.manager.caja:
        class: AppBundle\Manager\CajaManager
        arguments:
            # dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: AppBundle\Entity\Caja
    volume.loader.listener:
        class: AppBundle\Listener\VolumeLoader
        tags:
            - { name: doctrine.event_listener, event: postPersist }
